services:
  sandbox-postgresql:
    image: postgres:15
    container_name: sandbox-postgresql
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5429:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
