CREATE TABLE bank_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_time TIMESTAMP WITHOUT TIME ZONE,
    account_number VARCHAR(255),
    transaction_type VARCHAR(255),
    amount NUMERIC(38,2),
    balance NUMERIC(38,2),
    counterparty_name VARCHAR(255),
    memo VARCHAR(255),
    hash_value VARCHAR(255),
    PRIMARY KEY (id)
);